version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: wmm_postgres
    restart: always
    environment:
      POSTGRES_DB: wmm_db
      POSTGRES_USER: wmm_user
      POSTGRES_PASSWORD: wmm_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
